package product

import (
	"archive/zip"
	"bytes"
	"context"
	"encoding/xml"
	"fmt"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"
)

const maxDeliverableCells = 20000

// CreateDeliverable builds a portable Office/PDF file and stores it as an
// immutable Artifact. The request is deliberately content-oriented: callers do
// not get to inject raw package paths or XML into an OOXML archive.
func (s *Service) CreateDeliverable(ctx context.Context, input DeliverableInput) (Artifact, error) {
	input.Format = strings.ToLower(strings.TrimPrefix(strings.TrimSpace(input.Format), "."))
	input.Title, input.Actor = strings.TrimSpace(input.Title), strings.TrimSpace(input.Actor)
	if input.Actor == "" || input.Title == "" || utf8.RuneCountInString(input.Title) > 160 {
		return Artifact{}, fmt.Errorf("deliverable actor and title up to 160 characters are required")
	}
	if input.ProjectID != "" {
		if _, err := s.GetProject(ctx, input.ProjectID); err != nil {
			return Artifact{}, err
		}
	}
	if len(input.Paragraphs) > 2000 || len(input.Rows) > maxDeliverableCells || len(input.Slides) > 200 {
		return Artifact{}, fmt.Errorf("deliverable content exceeds the bounded package size")
	}
	cells := 0
	for _, row := range input.Rows {
		cells += len(row)
	}
	if cells > maxDeliverableCells {
		return Artifact{}, fmt.Errorf("spreadsheet exceeds %d cells", maxDeliverableCells)
	}

	var data []byte
	var mimeType, kind string
	var err error
	switch input.Format {
	case "docx":
		data, err = makeDOCX(input.Title, input.Paragraphs)
		mimeType, kind = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "office_document"
	case "xlsx":
		data, err = makeXLSX(input.Title, input.Rows, input.Paragraphs)
		mimeType, kind = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "office_spreadsheet"
	case "pptx":
		data, err = makePPTX(input.Title, input.Slides, input.Paragraphs)
		mimeType, kind = "application/vnd.openxmlformats-officedocument.presentationml.presentation", "office_presentation"
	case "pdf":
		data, err = makeBasicLatinPDF(input.Title, input.Paragraphs)
		mimeType, kind = "application/pdf", "pdf_document"
	default:
		return Artifact{}, fmt.Errorf("deliverable format must be docx, xlsx, pptx or pdf")
	}
	if err != nil {
		return Artifact{}, err
	}
	name := safeDeliverableName(input.Title) + "." + input.Format
	return s.CreateArtifact(ctx, ArtifactInput{ProjectID: input.ProjectID, SessionID: input.SessionID,
		Name: name, Kind: kind, MIMEType: mimeType, Content: string(data), Metadata: map[string]any{
			"created_by": input.Actor, "generator": "hermetrix-native", "format": input.Format,
			"editable": input.Format != "pdf",
		}})
}

func safeDeliverableName(title string) string {
	var out strings.Builder
	for _, r := range strings.ToLower(title) {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r):
			out.WriteRune(r)
		case r == ' ' || r == '-' || r == '_':
			if out.Len() > 0 && !strings.HasSuffix(out.String(), "-") {
				out.WriteByte('-')
			}
		}
		if out.Len() >= 80 {
			break
		}
	}
	name := strings.Trim(out.String(), "-")
	if name == "" {
		return "hermetrix-deliverable"
	}
	return name
}

func makeDOCX(title string, paragraphs []string) ([]byte, error) {
	if len(paragraphs) == 0 {
		paragraphs = []string{"Generated by Hermetrix."}
	}
	body := wordParagraph(title, true)
	for _, paragraph := range paragraphs {
		body += wordParagraph(paragraph, false)
	}
	files := map[string]string{
		"[Content_Types].xml": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`,
		"_rels/.rels":         `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`,
		"word/document.xml":   `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>` + body + `<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`,
	}
	return makeOOXML(files)
}

func wordParagraph(text string, title bool) string {
	properties := ""
	if title {
		properties = `<w:pPr><w:pStyle w:val="Title"/></w:pPr>`
	}
	return `<w:p>` + properties + `<w:r><w:t xml:space="preserve">` + xmlText(text) + `</w:t></w:r></w:p>`
}

func makeXLSX(title string, rows [][]string, paragraphs []string) ([]byte, error) {
	if len(rows) == 0 {
		rows = [][]string{{title}}
		for _, paragraph := range paragraphs {
			rows = append(rows, []string{paragraph})
		}
	}
	var sheet strings.Builder
	for rowIndex, row := range rows {
		sheet.WriteString(`<row r="` + strconv.Itoa(rowIndex+1) + `">`)
		for column, value := range row {
			cell := spreadsheetColumn(column+1) + strconv.Itoa(rowIndex+1)
			sheet.WriteString(`<c r="` + cell + `" t="inlineStr"><is><t xml:space="preserve">` + xmlText(value) + `</t></is></c>`)
		}
		sheet.WriteString(`</row>`)
	}
	files := map[string]string{
		"[Content_Types].xml":        `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>`,
		"_rels/.rels":                `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
		"xl/workbook.xml":            `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="` + xmlAttr(sheetTitle(title)) + `" sheetId="1" r:id="rId1"/></sheets></workbook>`,
		"xl/_rels/workbook.xml.rels": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>`,
		"xl/worksheets/sheet1.xml":   `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>` + sheet.String() + `</sheetData></worksheet>`,
	}
	return makeOOXML(files)
}

func spreadsheetColumn(index int) string {
	name := ""
	for index > 0 {
		index--
		name = string(rune('A'+index%26)) + name
		index /= 26
	}
	return name
}

func sheetTitle(title string) string {
	clean := strings.Map(func(r rune) rune {
		if strings.ContainsRune(`[]:*?/\\`, r) {
			return '-'
		}
		return r
	}, title)
	runes := []rune(clean)
	if len(runes) > 31 {
		runes = runes[:31]
	}
	if len(runes) == 0 {
		return "Sheet1"
	}
	return string(runes)
}

func makePPTX(title string, slides []DeliverableSlide, paragraphs []string) ([]byte, error) {
	if len(slides) == 0 {
		slides = []DeliverableSlide{{Title: title, Bullets: paragraphs}}
	}
	var overrides, slideIDs, slideRelationships strings.Builder
	files := map[string]string{
		"_rels/.rels":                                  `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/></Relationships>`,
		"ppt/slideMasters/slideMaster1.xml":            presentationMasterXML,
		"ppt/slideMasters/_rels/slideMaster1.xml.rels": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>`,
		"ppt/slideLayouts/slideLayout1.xml":            presentationLayoutXML,
		"ppt/slideLayouts/_rels/slideLayout1.xml.rels": `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>`,
		"ppt/theme/theme1.xml":                         presentationThemeXML,
	}
	for index, slide := range slides {
		n := index + 1
		overrides.WriteString(`<Override PartName="/ppt/slides/slide` + strconv.Itoa(n) + `.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`)
		slideIDs.WriteString(`<p:sldId id="` + strconv.Itoa(255+n) + `" r:id="rId` + strconv.Itoa(n+1) + `"/>`)
		slideRelationships.WriteString(`<Relationship Id="rId` + strconv.Itoa(n+1) + `" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide` + strconv.Itoa(n) + `.xml"/>`)
		files[`ppt/slides/slide`+strconv.Itoa(n)+`.xml`] = presentationSlideXML(slide)
		files[`ppt/slides/_rels/slide`+strconv.Itoa(n)+`.xml.rels`] = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>`
	}
	files["[Content_Types].xml"] = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>` + overrides.String() + `</Types>`
	files["ppt/presentation.xml"] = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst><p:sldIdLst>` + slideIDs.String() + `</p:sldIdLst><p:sldSz cx="12192000" cy="6858000" type="screen16x9"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>`
	files["ppt/_rels/presentation.xml.rels"] = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>` + slideRelationships.String() + `</Relationships>`
	return makeOOXML(files)
}

func presentationSlideXML(slide DeliverableSlide) string {
	body := ""
	for _, bullet := range slide.Bullets {
		body += `<a:p><a:pPr lvl="0"><a:buChar char="•"/></a:pPr><a:r><a:rPr lang="th-TH" sz="2200"/><a:t>` + xmlText(bullet) + `</a:t></a:r></a:p>`
	}
	if body == "" {
		body = `<a:p><a:endParaRPr lang="th-TH"/></a:p>`
	}
	return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/><p:sp><p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="685800" y="365760"/><a:ext cx="10820400" cy="914400"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="th-TH" sz="3200" b="1"/><a:t>` + xmlText(slide.Title) + `</a:t></a:r></a:p></p:txBody></p:sp><p:sp><p:nvSpPr><p:cNvPr id="3" name="Body"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="914400" y="1645920"/><a:ext cx="10287000" cy="4389120"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/></p:spPr><p:txBody><a:bodyPr wrap="square"/><a:lstStyle/>` + body + `</p:txBody></p:sp></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`
}

const presentationMasterXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld><p:clrMap accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" bg1="lt1" bg2="lt2" folHlink="folHlink" hlink="hlink" tx1="dk1" tx2="dk2"/><p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId2"/></p:sldLayoutIdLst></p:sldMaster>`

const presentationLayoutXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank"><p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr/></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`

const presentationThemeXML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="Hermetrix"><a:themeElements><a:clrScheme name="Hermetrix"><a:dk1><a:srgbClr val="10151D"/></a:dk1><a:lt1><a:srgbClr val="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="172033"/></a:dk2><a:lt2><a:srgbClr val="EAF7FA"/></a:lt2><a:accent1><a:srgbClr val="21D4D4"/></a:accent1><a:accent2><a:srgbClr val="7F6BFF"/></a:accent2><a:accent3><a:srgbClr val="9CFF38"/></a:accent3><a:accent4><a:srgbClr val="48A8FF"/></a:accent4><a:accent5><a:srgbClr val="FFCF70"/></a:accent5><a:accent6><a:srgbClr val="FF7B7B"/></a:accent6><a:hlink><a:srgbClr val="48A8FF"/></a:hlink><a:folHlink><a:srgbClr val="7F6BFF"/></a:folHlink></a:clrScheme><a:fontScheme name="Hermetrix"><a:majorFont><a:latin typeface="Aptos Display"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont><a:minorFont><a:latin typeface="Aptos"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont></a:fontScheme><a:fmtScheme name="Hermetrix"><a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="9525"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements></a:theme>`

// The built-in PDF writer uses a standard PDF font. It therefore refuses text
// outside printable Basic Latin instead of producing a file whose Thai or CJK
// text silently renders as empty boxes. DOCX/PPTX/XLSX remain full UTF-8 OOXML.
func makeBasicLatinPDF(title string, paragraphs []string) ([]byte, error) {
	lines := append([]string{title}, paragraphs...)
	for _, line := range lines {
		for _, r := range line {
			if r == '\n' || r == '\t' || (r >= 32 && r <= 126) {
				continue
			}
			return nil, fmt.Errorf("native PDF currently supports printable Basic Latin only; use DOCX or PPTX for Unicode text")
		}
	}
	var content strings.Builder
	content.WriteString("BT /F1 20 Tf 72 760 Td ")
	for index, line := range lines {
		if index == 1 {
			content.WriteString(" /F1 11 Tf")
		}
		if index > 0 {
			content.WriteString(" 0 -24 Td")
		}
		content.WriteString(" (" + pdfEscape(line) + ") Tj")
	}
	content.WriteString(" ET")
	stream := content.String()
	objects := []string{
		`<< /Type /Catalog /Pages 2 0 R >>`,
		`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`,
		`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>`,
		`<< /Length ` + strconv.Itoa(len(stream)) + ` >>` + "\nstream\n" + stream + "\nendstream",
		`<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`,
	}
	var output bytes.Buffer
	output.WriteString("%PDF-1.7\n%\xE2\xE3\xCF\xD3\n")
	offsets := make([]int, len(objects)+1)
	for index, object := range objects {
		offsets[index+1] = output.Len()
		fmt.Fprintf(&output, "%d 0 obj\n%s\nendobj\n", index+1, object)
	}
	xref := output.Len()
	fmt.Fprintf(&output, "xref\n0 %d\n0000000000 65535 f \n", len(objects)+1)
	for index := 1; index <= len(objects); index++ {
		fmt.Fprintf(&output, "%010d 00000 n \n", offsets[index])
	}
	fmt.Fprintf(&output, "trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n", len(objects)+1, xref)
	return output.Bytes(), nil
}

func pdfEscape(value string) string {
	return strings.NewReplacer(`\\`, `\\\\`, `(`, `\\(`, `)`, `\\)`, "\n", `\n`, "\r", "").Replace(value)
}

func makeOOXML(files map[string]string) ([]byte, error) {
	var output bytes.Buffer
	archive := zip.NewWriter(&output)
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, filepath.ToSlash(name))
	}
	sort.Strings(names)
	for _, name := range names {
		header := &zip.FileHeader{Name: name, Method: zip.Deflate}
		header.SetModTime(time.Date(1980, 1, 1, 0, 0, 0, 0, time.UTC))
		writer, err := archive.CreateHeader(header)
		if err != nil {
			return nil, err
		}
		if _, err := writer.Write([]byte(files[name])); err != nil {
			return nil, err
		}
	}
	if err := archive.Close(); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

func xmlText(value string) string {
	var output bytes.Buffer
	_ = xml.EscapeText(&output, []byte(value))
	return output.String()
}

func xmlAttr(value string) string { return xmlText(value) }
