package worker

import (
	"time"

	"hermetrix-harness/internal/providers"
)

// Task is the complete, caller-curated contract for one bounded worker call.
// Files contain source text rather than paths for the worker to discover.
type Task struct {
	ID                 string            `json:"id,omitempty"`
	Kind               string            `json:"kind,omitempty"`
	Brief              string            `json:"brief"`
	AcceptanceCriteria []string          `json:"acceptance_criteria,omitempty"`
	Constraints        []string          `json:"constraints,omitempty"`
	RecommendedChecks  []string          `json:"recommended_checks,omitempty"`
	Files              map[string]string `json:"files"`
	MaxOutputTokens    int               `json:"max_output_tokens,omitempty"`
}

// TextEdit replaces one exact, unique piece of the supplied preimage. Keeping
// the match text in the proposal makes a compact change independently
// checkable without trusting line numbers generated by a model.
type TextEdit struct {
	Old string `json:"old"`
	New string `json:"new"`
}

type Change struct {
	Path         string `json:"path"`
	BeforeSHA256 string `json:"before_sha256"`
	Content      string `json:"content"`
	Strategy     string `json:"strategy"`
}

type Result struct {
	Status            string          `json:"status"`
	TaskID            string          `json:"task_id,omitempty"`
	ProposalID        string          `json:"proposal_id"`
	InputSHA256       string          `json:"input_sha256"`
	Summary           string          `json:"summary,omitempty"`
	Assumptions       []string        `json:"assumptions,omitempty"`
	Risks             []string        `json:"risks,omitempty"`
	RecommendedChecks []string        `json:"recommended_checks,omitempty"`
	Changes           []Change        `json:"changes"`
	Usage             providers.Usage `json:"usage"`
}

type Phase string

const (
	PhaseValidatingInput    Phase = "validating_input"
	PhaseRequestingProvider Phase = "requesting_provider"
	PhaseValidatingProposal Phase = "validating_proposal"
	PhaseCompleted          Phase = "completed"
)

// ProgressEvent contains no task or provider content, so it is safe to show in
// a UI or write to a local operational log.
type ProgressEvent struct {
	Sequence int       `json:"sequence"`
	Phase    Phase     `json:"phase"`
	At       time.Time `json:"at"`
}

type Options struct {
	Progress          func(ProgressEvent)
	Now               func() time.Time
	HeartbeatInterval time.Duration
	// BeforeProviderRequest runs after all local validation and immediately
	// before the request crosses the provider boundary. Coordinators use it to
	// durably mark an effect dispatched without classifying rejected input as
	// an uncertain external effect.
	BeforeProviderRequest func() error
}
